void init_GPIO(void);
void init_ADC(void);
void init_TIM5(void);
void init_DAC(void);
void init_TIM2();
void init_DSP();
void initLookUpTan(void);
//void init_tim3(void);
void setup_adc();
uint16_t selectRatio(uint16_t ratio);
void togglexn(GPIO_TypeDef *port, int n);
void init_tim7(void);
void init_tim3(void);